In [1]:
import pandas as pd
tabela = pd.read_csv("dados/MICRODADOS_ENEM_2000.csv", sep=",", encoding="utf-8")

pd.set_option('display.max_columns', None)
display(tabela)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,TP_ST_CONCLUSAO,TP_PRESENCA,CO_PROVA,VL_PERC_COMP1,VL_PERC_COMP2,VL_PERC_COMP3,VL_PERC_COMP4,VL_PERC_COMP5,NU_NOTA_OBJETIVA,TX_RESPOSTAS_OBJETIVA,TX_GABARITO_OBJETIVA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,IN_QSE
0,1,2000,3,F,3304706,SANTO ANTONIO DE PADUA,33,RJ,2.0,1,A,48.48,50.98,52.38,45.45,51.11,50.79,BDDEADABBADDEADDCCEDBDDBCCAADCDBBDECCDCDCBCCBB...,ABCEBDEBBADDDADDBEAEBADACCAADDDCBACECBECEBADCB...,P,75.0,62.5,50.0,62.5,75.0,65.0,1
1,2,2000,2,F,3302304,LAJE DO MURIAE,33,RJ,2.0,1,A,27.27,29.41,23.81,30.30,31.11,28.57,EDAEBDEBBADECCEDBAEBCAECBDBAAECCBDEEDCCBAACEED...,ABCEBDEBBADDDADDBEAEBADACCAADDDCBACECBECEBADCB...,P,75.0,75.0,75.0,75.0,50.0,70.0,1
2,3,2000,3,F,3300605,BOM JESUS DO ITABAPOANA,33,RJ,2.0,1,V,48.48,31.37,38.10,42.42,35.56,39.68,DDEEAEEAECDBDBDAADBEDCEBDDADBDEEBEDDBAEDBCDECE...,ACECBECEBADCABCEBDAEDDEBDCDDDDEBBADDDADDBEAEBA...,P,87.5,75.0,62.5,75.0,50.0,70.0,1
3,4,2000,3,F,3304706,SANTO ANTONIO DE PADUA,33,RJ,2.0,1,V,57.58,62.75,69.05,69.70,68.89,68.25,ACCDBEAEBCDCADCEEDAEDDBBDBDDDDEBBCDACAEDBDADBE...,ACECBECEBADCABCEBDAEDDEBDCDDDDEBBADDDADDBEAEBA...,P,75.0,75.0,75.0,87.5,62.5,75.0,1
4,5,2000,2,F,3113305,CARANGOLA,31,MG,2.0,1,B,42.42,37.25,40.48,36.36,37.78,39.68,CBADACDDCEDEEDBEADDDDDEDDDEECDDCBDEEDDBDDDEDDB...,DBEAEBABCEBDEBBADDDADADACCAADDDCBACECBECEBADCB...,P,87.5,75.0,75.0,87.5,87.5,82.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,5138,2000,1,F,4210100,MAFRA,42,SC,2.0,1,A,33.33,29.41,23.81,27.27,24.44,28.57,ABBDADDBCEDACABABBBAAABEDECADDDCCDAADDEAEEDDBC...,ABCEBDEBBADDDADDBEAEBADACCAADDDCBACECBECEBADCB...,P,62.5,50.0,50.0,62.5,50.0,55.0,1
4995,5139,2000,1,F,4209102,JOINVILLE,42,SC,2.0,1,V,51.52,41.18,33.33,42.42,37.78,41.27,CCDEBEDAECECCDBDAEE*DCEBDCDDDDCABAEDBBACBEECDD...,ACECBECEBADCABCEBDAEDDEBDCDDDDEBBADDDADDBEAEBA...,P,37.5,37.5,50.0,37.5,37.5,40.0,1
4996,5140,2000,3,F,4209102,JOINVILLE,42,SC,2.0,1,A,54.55,50.98,54.76,51.52,57.78,52.38,ABCEBDDBBCAEDBEDBBEDCCEDDDAADDDCBAEEBBCBAEAECA...,ABCEBDEBBADDDADDBEAEBADACCAADDDCBACECBECEBADCB...,P,75.0,62.5,50.0,75.0,37.5,60.0,1
4997,5141,2000,2,F,4209102,JOINVILLE,42,SC,2.0,1,A,39.39,35.29,38.10,33.33,35.56,36.51,ADACBDDABABDDABDBADEDDCEDBCADDBCACCBECCBDBBCBC...,ABCEBDEBBADDDADDBEAEBADACCAADDDCBACECBECEBADCB...,P,75.0,75.0,50.0,75.0,25.0,60.0,1
4998,5142,2000,3,F,4202909,BRUSQUE,42,SC,2.0,1,V,27.27,29.41,21.43,27.27,26.67,26.98,DAEBEDECEECEADECBEABCAECACDCDECBCEBDCAEDCDDEDD...,ACECBECEBADCABCEBDAEDDEBDCDDDDEBBADDDADDBEAEBA...,P,50.0,50.0,50.0,50.0,62.5,52.5,1

In [2]:
# LISTA OS MUNICIPIOS DISPONIVEIS NOS DADOS
def lista_municipios():
    municipios = tabela[["NO_MUNICIPIO_RESIDENCIA"]].groupby("NO_MUNICIPIO_RESIDENCIA").sum()
    pd.set_option('display.max_rows', None)
    
    return municipios

In [3]:
# PESQUISANDO UM MUNICIPIO
def busca_municipio(busca):
    nome_municipio = busca
    municipio = tabela[tabela.NO_MUNICIPIO_RESIDENCIA==nome_municipio].count()[0]
    print("Número de aparições do municipio '{}' = {}".format(nome_municipio, municipio))
    tabela_municipio = tabela[tabela.NO_MUNICIPIO_RESIDENCIA==nome_municipio]

    return tabela_municipio

# CHECANDO CANDIDATOS QUE ESTIVERAM PRESENTES E AUSENTES NA PROVA
# PARA OBTER CANDITOS PRESENTES BASTA INSERIR 1 NA VARIAVEL VALOR
# PARA OBTER CANDITOS AUSENTES BASTA INSERIR 0 NA VARIAVEL VALOR
def obter_candidatos_por_status(municipio, valor):
    if(valor == 0):
        tabela_municipio = busca_municipio(municipio)
        candidatos_ausentes = tabela_municipio[tabela_municipio.TP_PRESENCA==valor]
        num_ausentes = candidatos_ausentes.count()[0]
        display(candidatos_ausentes)
        print("Número de candidatos ausentes durante a prova no municipio de '{}' = {}".format(municipio, num_ausentes))
        return candidatos_ausentes
    elif(valor == 1):
        tabela_municipio = busca_municipio(municipio)
        candidatos_presentes = tabela_municipio[tabela_municipio.TP_PRESENCA==valor]
        num_presentes = candidatos_presentes.count()[0]
        display(candidatos_presentes)
        print("Número de candidatos presentes durante a prova no municipio de '{}' = {}".format(municipio, num_presentes))
        return candidatos_presentes

obter_candidatos_por_status("JOINVILLE", 0)

Número de aparições do municipio 'JOINVILLE' = 320

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,TP_ST_CONCLUSAO,TP_PRESENCA,CO_PROVA,VL_PERC_COMP1,VL_PERC_COMP2,VL_PERC_COMP3,VL_PERC_COMP4,VL_PERC_COMP5,NU_NOTA_OBJETIVA,TX_RESPOSTAS_OBJETIVA,TX_GABARITO_OBJETIVA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,IN_QSE
4007,4147,2000,3,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4069,4209,2000,3,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4075,4215,2000,2,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4153,4294,2000,4,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4154,4295,2000,1,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4161,4302,2000,1,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4163,4304,2000,1,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4209,4350,2000,14,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4250,4391,2000,2,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4264,4405,2000,7,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4295,4436,2000,10,M,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4307,4448,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4474,4617,2000,2,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4479,4622,2000,4,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4495,4638,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4504,4647,2000,3,M,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4505,4648,2000,2,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4509,4652,2000,3,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4637,4781,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4650,4794,2000,2,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4660,4804,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4692,4836,2000,4,M,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4695,4839,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4699,4843,2000,1,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4726,4870,2000,3,M,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4732,4876,2000,2,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4733,4877,2000,1,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4784,4928,2000,2,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4935,5079,2000,4,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4969,5113,2000,4,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4973,5117,2000,1,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4979,5123,2000,1,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0

Número de candidatos ausentes durante a prova no municipio de 'JOINVILLE' = 32

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,TP_ST_CONCLUSAO,TP_PRESENCA,CO_PROVA,VL_PERC_COMP1,VL_PERC_COMP2,VL_PERC_COMP3,VL_PERC_COMP4,VL_PERC_COMP5,NU_NOTA_OBJETIVA,TX_RESPOSTAS_OBJETIVA,TX_GABARITO_OBJETIVA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,IN_QSE
4007,4147,2000,3,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4069,4209,2000,3,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4075,4215,2000,2,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4153,4294,2000,4,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4154,4295,2000,1,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4161,4302,2000,1,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4163,4304,2000,1,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4209,4350,2000,14,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4250,4391,2000,2,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4264,4405,2000,7,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4295,4436,2000,10,M,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4307,4448,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4474,4617,2000,2,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4479,4622,2000,4,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4495,4638,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4504,4647,2000,3,M,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4505,4648,2000,2,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4509,4652,2000,3,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4637,4781,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4650,4794,2000,2,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4660,4804,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4692,4836,2000,4,M,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4695,4839,2000,3,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4699,4843,2000,1,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4726,4870,2000,3,M,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4732,4876,2000,2,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4733,4877,2000,1,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4784,4928,2000,2,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4935,5079,2000,4,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4969,5113,2000,4,F,4209102,JOINVILLE,42,SC,1.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4973,5117,2000,1,M,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0
4979,5123,2000,1,F,4209102,JOINVILLE,42,SC,2.0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,F,0.0,0.0,0.0,0.0,0.0,0.0,0

In [4]:
def BinarioParaDecimal(valor_binario):
    valor_decimal = int(valor_binario, 2)
    return valor_decimal

def BinarioParaString(valor_binario):
    teste = ''
    for i in range(0, len(result), 8):
        temp = result[i:i + 8]
        resposta = BinarioParaDecimal(temp)
        teste = teste + chr(resposta)
        print(teste)
        
    return teste

# SALVA OS DADOS EM UM ARQUIVO BINARIO
# PARA ISSO, BASTA ESCOLHER UM MUNICIPIO E DIZER SE DESEJA SALVAR OS CANDIDATOS PRESENTES OU AUSENTES
# PARA CANDIDATOS AUSENTES INSIRA O VALOR 0, PARA CANDIDATOS PRESENTES INSIRA O VALOR 1
# A ULTIMA VARIAVEL A SER INSERIDA EH O NOME DO ARQUIVO EM QUE DESEJA SALVAR OS DADOS
def salva_dados(municipio, valor, nome_arquivo):
    with open(nome_arquivo + '.bin', 'w') as dados:
        i = 0
        while(i <= len(tabela)-1):
            if(tabela.loc[i][5] == municipio and tabela.loc[i][9] == valor):
                j = 0
                while(j <= 26): 
                    dado_string = str(tabela.loc[i][j])
                    result = ''.join(format(ord(c), '08b') for c in dado_string)
                    dados.write(result)
                    j = j + 1
                dados.write("\n")
            i = i + 1
        print("DADOS SALVOS COM SUCESSO!")
    
salva_dados("JOINVILLE", 0, "lista_ausentes")
salva_dados("JOINVILLE", 1, "lista_presentes")

DADOS SALVOS COM SUCESSO!
DADOS SALVOS COM SUCESSO!